### ISSUE TITLE
Getting this to work on Windows

### ISSUE THREAD

**Issue by ghost** [LucasSheng/avatar-net#1]
Thanks for sharing this. I wanted to try running it on local GPU on Windows. Was able to get it to work with several tweaks. Posting in case anyone else wants to try.

windows fork: https://github.com/noido/avatar-net

edit details: https://github.com/noido/avatar-net/blob/master/readme_windows_tweaks.txt

The most notable obstacle was that the pretrained model download (Google Drive) linked in the repo was missing a checkpoint file to specify model_checkpoint_path. That caused a tensorflow function to return None instead of the correct model path, which caused a cascade of wonderful error messages down the line.

**Comment by LucasSheng** [comment]
Thank you for sharing us these messages.

For the `model_checkpoint_path issue`, I suggest to create a file named as `checkpoint` in the directory where you store the checkpoint, including the following line:

    model_checkpoint_path: "/where/you/store/the/checkpoint/model.ckpt-120000"
